// App Notification
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION";
export const TOGGLE_NOTIFICATION_OFF = "TOGGLE_NOTIFICATION_OFF";

// Places
export const FETCH_PLACES = "FETCH_PLACES";
export const UPDATE_COORDINATES = "UPDATE_COORDINATES";
export const UPDATE_BOUNDS = "UPDATE_BOUNDS";
export const MAP_CARD_CLICKED = "MAP_CARD_CLICKED";
export const FILTER_PLACES = "FILTER_PLACES";

// Weather
export const FETCH_WEATHER_DATA = "FETCH_WEATHER_DATA";
